# Generated by Django 4.2.1 on 2023-05-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
    ]
